services:
  - type: web
    name: lab-desenv-soft-todo-list
    runtime: static
    buildCommand: npm run build
    envVars:
      # OBS: Essa variável de ambiente deve ser configurada manualmente no
      # painel do Render, pois o blueprint não possui uma forma de obter o
      # endereço publico do serviço de API.
      - key: VITE_API_URL
        value: http://<host>:<port>/api/
    staticPublishPath: ./dist
    rootDir: front-end
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    runtime: docker
    name: lab-desenv-soft-todo-list-api
    region: oregon
    plan: free
    rootDir: back-end
    healthCheckPath: /api/healthz
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: database
      # OBS: Essa variável de ambiente deve ser configurada manualmente no
      # painel do Render, usando os valores em DATABASE_HOST, DATABASE_PORT e
      # DATABASE_NAME, pois o blueprint não suporta interpolação de variáveis
      # de ambiente.
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://<host>:<port>/<database>
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver

databases:
  - name: lab-desenv-soft-todo-list-db
    postgresMajorVersion: "16"
    region: oregon
    plan: free
    databaseName: todolistdb
    user: todolistdefaultuser
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
