services:
  - type: web
    name: lab-desenv-soft-todo-list
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    rootDir: front-end
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    runtime: docker
    name: lab-desenv-soft-todo-list-api
    region: oregon
    plan: free
    rootDir: back-end
    healthCheckPath: /api/healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: connectionString
      - key: DATABASE_USER
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: lab-desenv-soft-todo-list-db
          property: database

databases:
  - name: lab-desenv-soft-todo-list-db
    postgresMajorVersion: "16"
    region: oregon
    plan: free
    databaseName: todolistdb
    user: todolistdefaultuser
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
