@startuml c4model_nivel_3_diagrama_de_componentes
!include <C4/C4_Component>

LAYOUT_WITH_LEGEND()

title Diagrama de componentes do sistema de Lista de Tarefas - API Application

Container(spa, "Single-Page App", "JavaScript, React.js", "Fornece toda a funcionalidade do Sistema de Lista de Tarefas para os clientes por meio de seu navegador web")
ContainerDb(database, "Banco de dados", "PostgreSQL", "Armazena informações de registros de tarefas")

Container_Boundary(api, "API Application") {
    Component(task_controller, "Task Controller", "Rest Controller", "Permite aos usuários gerenciar suas tarefas")
    Component(task_service, "Task Service", "Spring Service Bean", "Provê funcionalidades de gerenciamento de tarefas")
    Component(task_repository, "Task Repository", "JPA Repository", "Lida com a persistência de tarefas")


    Rel(task_controller, task_service, "Utiliza")
    Rel(task_service, task_repository, "Utiliza")
    Rel(task_repository, database, "Lê e escreve", "JDBC")
}

Rel(spa, task_controller, "Uses", "JSON/HTTPS")

@enduml