@startuml diagrama_de_sequencia_frontend_002_criar_tarefa
actor Usuário as u
participant SPA as "Single-Page App"
participant API as "API Application"

u -> SPA: Interage com a interface da aplicação

alt Criação de Tarefa
    SPA -> API: POST /tasks
    API --> SPA: Resposta 201 Created
end

alt Busca de Tarefas Atualizada
    SPA -> API: GET /tasks
    API --> SPA: Lista de tarefas atualizada
    SPA -> SPA: Exibe a lista de tarefas na interface
end

@enduml
