@startuml diagrama_de_sequencia_frontend_004_deletar_tarefa
actor Usuário as u
participant SPA as "Single-Page App"
participant API as "API Application"

u -> SPA: Interage com a interface da aplicação

alt Exclusão de Tarefa
    SPA -> API: DELETE /tasks/{id}
    API --> SPA: Resposta 204 No Content
end

alt Busca de Tarefas Atualizada
    SPA -> API: GET /tasks
    API --> SPA: Lista de tarefas atualizada
    SPA -> SPA: Exibe a lista de tarefas na interface
end

@enduml
